version: '2'

services:
  elasticsearch:
    image: elasticsearch:2.4.4
    ports:
       - "9200:9200"
       - "9300:9300"
    command: elasticsearch --cluster.name=snag
    networks:
      - snag

  spring:
    build: ./spring
    ports:
       - "8000:8000"
    depends_on:
      - elasticsearch
    environment:
      - SPRING.DATA.ELASTICSEARCH.CLUSTERNODES=elasticsearch:9300
    networks:
      - snag

networks:
  snag:
    driver: bridge